### PR TITLE
fix: remove dependency on google-cloud-bigquery (cyclic dep)

### LINKED ISSUE #1249: Refactor write client code to use the generated instead of the handwritten BigQuery client
The fact that google-cloud-bigquerystorage Write client (v1beta2) is using google-cloud-bigquery [as a dependency](https://github.com/googleapis/java-bigquerystorage/blob/master/google-cloud-bigquerystorage/pom.xml#L146-L149) means it would introduce a cyclic dependency when we integrate it into google-cloud-bigquery for high throughput Write in the future. This is also currently blocking us from using google-cloud-bigquerystorage client in google-cloud-bigquery for the Read API features (v1). We have found a temporary workaround to unblock ourselves on the Read side but **this refactoring is necessary before we GA this client**.

Specifically, 3 classes require full refactoring:
1. `/usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:`
2. `/usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:`
3. `/usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java:`

Full trace:
```
 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project google-cloud-bigquerystorage: Compilation failure: Compilation failure: 
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[18,33] cannot find symbol
[ERROR]   symbol:   class Field
[ERROR]   location: package com.google.cloud.bigquery
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[19,33] cannot find symbol
[ERROR]   symbol:   class Schema
[ERROR]   location: package com.google.cloud.bigquery
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[20,33] cannot find symbol
[ERROR]   symbol:   class StandardSQLTypeName
[ERROR]   location: package com.google.cloud.bigquery
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[25,36] package Field does not exist
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[31,31] cannot find symbol
[ERROR]   symbol:   class StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[53,48] cannot find symbol
[ERROR]   symbol:   class Schema
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[67,53] cannot find symbol
[ERROR]   symbol:   class Field
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[18,33] cannot find symbol
[ERROR]   symbol:   class BigQuery
[ERROR]   location: package com.google.cloud.bigquery
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[19,33] cannot find symbol
[ERROR]   symbol:   class Field
[ERROR]   location: package com.google.cloud.bigquery
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[20,33] cannot find symbol
[ERROR]   symbol:   class LegacySQLTypeName
[ERROR]   location: package com.google.cloud.bigquery
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[21,33] cannot find symbol
[ERROR]   symbol:   class Schema
[ERROR]   location: package com.google.cloud.bigquery
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[22,33] cannot find symbol
[ERROR]   symbol:   class Table
[ERROR]   location: package com.google.cloud.bigquery
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[23,33] cannot find symbol
[ERROR]   symbol:   class TableId
[ERROR]   location: package com.google.cloud.bigquery
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[24,41] package com.google.cloud.bigquery.testing does not exist
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[46,11] cannot find symbol
[ERROR]   symbol:   class BigQuery
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[74,31] cannot find symbol
[ERROR]   symbol:   class BigQuery
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[99,49] cannot find symbol
[ERROR]   symbol:   class BigQuery
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[104,11] cannot find symbol
[ERROR]   symbol:   class TableId
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[257,47] cannot find symbol
[ERROR]   symbol:   class Field
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[310,7] cannot find symbol
[ERROR]   symbol:   class Field
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[409,7] cannot find symbol
[ERROR]   symbol:   class Schema
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java:[22,33] cannot find symbol
[ERROR]   symbol:   class Schema
[ERROR]   location: package com.google.cloud.bigquery
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java:[208,62] cannot find symbol
[ERROR]   symbol:   class Schema
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.JsonStreamWriter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[27,16] package Field does not exist
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[28,16] package Field does not exist
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[29,16] package Field does not exist
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[44,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[43,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[42,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[41,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[40,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[39,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[38,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[37,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[36,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[35,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[34,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[33,16] cannot find symbol
[ERROR]   symbol:   variable StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[32,32] cannot find symbol
[ERROR]   symbol:   class StandardSQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.BQV2ToBQStorageConverter
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BQV2ToBQStorageConverter.java:[70,46] package Field does not exist
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[86,7] cannot find symbol
[ERROR]   symbol:   class RemoteBigQueryHelper
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[86,45] cannot find symbol
[ERROR]   symbol:   variable RemoteBigQueryHelper
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[109,12] cannot find symbol
[ERROR]   symbol:   variable TableId
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[264,12] cannot find symbol
[ERROR]   symbol:   variable REPEATED
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[274,12] cannot find symbol
[ERROR]   symbol:   variable REQUIRED
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[284,12] cannot find symbol
[ERROR]   symbol:   variable NULLABLE
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[318,5] cannot find symbol
[ERROR]   symbol:   class LegacySQLTypeName
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[365,13] cannot find symbol
[ERROR]   symbol:   variable Schema
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[421,10] cannot find symbol
[ERROR]   symbol:   class Field
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[442,10] cannot find symbol
[ERROR]   symbol:   class Field
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[450,59] package Field does not exist
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[512,5] cannot find symbol
[ERROR]   symbol:   class TableId
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[513,5] cannot find symbol
[ERROR]   symbol:   class Table
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] /usr/local/google/home/stephwang/Desktop/stephdev/java-bigquerystorage/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/SchemaCompatibility.java:[514,5] cannot find symbol
[ERROR]   symbol:   class Schema
[ERROR]   location: class com.google.cloud.bigquery.storage.v1beta2.SchemaCompatibility
[ERROR] -> [Help 1]
```

### PR DESCRIPTION
**Pull request by stephaniewang526**
Fixes #1249

### CODE REVIEW

File: google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java [hunk 1]
```diff
@@ -339,8 +363,7 @@ public void testJsonStreamWriterWithDefaultStream()
     bigquery.create(tableInfo);
     TableName parent = TableName.of(ServiceOptions.getDefaultProjectId(), DATASET, tableName);
     try (JsonStreamWriter jsonStreamWriter =
-        JsonStreamWriter.newBuilder(parent.toString(), tableInfo.getDefinition().getSchema())
```
Comment (yirutang) [inline google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java:342]: This changes public interface, could it break users?

Comment (stephaniewang526) [reply google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java:342]: yes it would break preview users

File: samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java [hunk 2]
```diff
@@ -39,27 +37,31 @@ public static void runWriteToDefaultStream()
     String projectId = "MY_PROJECT_ID";
     String datasetName = "MY_DATASET_NAME";
     String tableName = "MY_TABLE_NAME";
-
-    writeToDefaultStream(projectId, datasetName, tableName);
+    TableFieldSchema strField =
```
Comment (yirutang) [inline samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java:40]: I would suggest keep the sample the way it is. Move BQV2ToBQStorageConverter.java into sample as a lib, and the sample would still do a GetTable(), use BQV2ToBQStorageConverter to convert the schema and then use JsonWriter. It doesn't need to block this PR.

**Review by yirutang — APPROVED** [review]

File: samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java (hunk 2 above)
Comment (stephaniewang526) [reply samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java:40]: Sure. Will make this change in a separate PR.

File: .kokoro/dependencies.sh [hunk 3]
```diff
@@ -47,11 +47,11 @@ function completenessCheck() {
   # This is stripped from the output as it is not present in the flattened pom.
   # Only dependencies with 'compile' or 'runtime' scope are included from original dependency list.
   msg "Generating dependency list using original pom..."
-  mvn dependency:list -f pom.xml -DincludeScope=runtime -Dsort=true | grep '\[INFO]    .*:.*:.*:.*:.*' | sed -e 's/ --.*//' >.org-list.txt
+  mvn dependency:list -f pom.xml -DincludeScope=runtime -DexcludeArtifactIds=gson,commons-codec,commons-logging,opencensus-contrib-http-util,httpclient,httpcore -Dsort=true | grep '\[INFO]    .*:.*:.*:.*:.*' | sed -e 's/ --.*//' >.org-list.txt
```
Comment (tswast) [inline .kokoro/dependencies.sh:50]: Where is this exclusion list coming from? A template?

**Review by tswast — APPROVED** [review]
I imagine you'll want a helper in the `google-cloud-bigquery` client for converting to the BQ Storage `TableSchema` once the v1 protos are available. That should be possible without a circular dependency.

File: .kokoro/dependencies.sh (hunk 3 above)
Comment (stephaniewang526) [reply .kokoro/dependencies.sh:50]: Yes indeed. It comes from synthtool. There is a bug in maven-dependency-plugin which is causing this issue: https://issues.apache.org/jira/browse/MDEP-737 
So we temporarily add this exclusion as a workaround.
